import { StyleSheet } from "@react-pdf/renderer";

const main = StyleSheet.create({
  body: {
    paddingTop: 72,
    paddingLeft: 72,
    paddingBottom: 36,
    paddingRight: 36,
    backgroundColor: "white",
    fontSize: 10,
    fontFamily: "Inter",
  },
  header: {
    fontSize: 14,
    marginBottom: 40,
    textAlign: "center",
    fontWeight: "semibold",
  },
  sub_header: {
    fontSize: 11,
    marginTop: 20,
    marginBottom: 5,
    fontWeight: "semibold",
  },
  flex_col: {
    display: "flex",
    flexDirection: "col",
    gap: "10px",
    fontSize: 11,
  },
  flex_row: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
  },
  row: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  label: {
    minWidth: 110,
  },
  table: {
    fontSize: 10,
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: "auto",
    flexDirection: "row",
    borderStyle: "solid",
    borderWidth: 0,
    borderBottomWidth: 1,
  },
  tableHead: {
    width: "100%",
    textAlign: "center",
    borderStyle: "solid",
    borderWidth: 0,
    borderRightWidth: 1,
    paddingTop: 3,
    paddingBottom: 3,
    fontWeight: "bold",
  },
  tableColHeader: {
    width: "30%",
    borderStyle: "solid",
    borderWidth: 0,
    borderRightWidth: 1,
    fontWeight: "bold",
  },

  tableCol: {
    width: "70%",
    borderStyle: "solid",
    borderWidth: 0,
    borderRightWidth: 1,
  },
  tableCell: {
    margin: 3,
    lineHeight: 1.25,
  },
});

const cover = StyleSheet.create({
  container: {
    marginTop: 80,
    fontSize: 14,
    marginBottom: 40,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    lineHeight: 1.25,
    fontWeight: "semibold",
  },
  image: {
    height: 119,
    width: 114,
    marginBottom: 15,
  },
  middleContainer: {
    marginVertical: 90,
    gap: 20,
  },
  name: {
    fontSize: 12,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
  },
  nisn: {
    fontSize: 12,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
  },
  footer: {
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
  },
});

const tables_b = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingLeft: 65,
    paddingBottom: 65,
    paddingRight: 35,
    backgroundColor: "white",
    fontSize: 10,
  },
  sub_header: {
    fontSize: 11,
    marginTop: 20,
    marginBottom: 5,
    fontWeight: "bold",
  },
  sub_mini_header: {
    fontSize: 10,
    marginTop: 5,
    marginBottom: 5,
    fontWeight: "bold",
  },
  label: {
    paddingTop: 3,
    paddingBottom: 3,
  },
  labelSpan: {
    display: "absolute",
    transformOriginX: 30,
    transformOriginY: 10,
    paddingTop: 10.8,
    paddingBottom: 3,
  },
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: "auto",
    flexDirection: "row",
    lineHeight: 1.25,
  },
  tableNoHead: {
    width: "6%",
    margin: "auto",
    display: "flex",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderRightWidth: 1,
    fontWeight: "semibold",
  },
  tableMuatanHead: {
    width: "20%",
    margin: "auto",
    display: "flex",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderRightWidth: 1,
    fontWeight: "semibold",
  },
  tablePKHead: {
    width: "37%",
    margin: "auto",
    display: "flex",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderRightWidth: 1,
    fontWeight: "semibold",
  },
  tablePKSubHead: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  tablePKSubHeadNP: {
    width: "12%",
    textAlign: "center",
    margin: "auto",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    paddingTop: 2,
  },
  tablePKSubHeadDesc: {
    width: "76%",
    textAlign: "center",
    margin: "auto",
    borderStyle: "solid",
    borderTopWidth: 1,
    paddingTop: 2,
  },
  tablePKSubHeadNone: {
    width: "100%",
    fontSize: 3,
    textAlign: "center",
    margin: "auto",
    borderStyle: "solid",
    paddingTop: 4,
    color: "white",
  },

  tableTwo: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 0,
    borderLeftWidth: 1,
  },
  tableCol: {
    width: "6%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColLokal: {
    width: "6%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColMuatan: {
    width: "20%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColMuatanLokal: {
    width: "94%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColNP: {
    width: "4.42%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColDesc: {
    width: "28.16%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCell: {
    textAlign: "start",
    margin: "auto",
    marginTop: 5,
    fontSize: 10,
  },
  tableCellEnd: {
    textAlign: "center",
    margin: "auto",
    marginLeft: 8,
    marginTop: 5,
    fontSize: 10,
  },
  tableCellLokal: {
    textAlign: "start",
    margin: "auto",
    marginTop: 5,
    marginBottom: 4,
    fontSize: 10,
  },
  tableCellMuatan: {
    margin: "auto",
    marginTop: 5,
    marginLeft: 3,
    marginRight: 3,
    fontSize: 10,
  },
  tableCellMuatanLokal: {
    margin: "auto",
    marginTop: 5,
    marginBottom: 4,
    marginLeft: 3,
    marginRight: 3,
    fontSize: 10,
    fontWeight: "semibold",
  },
  tableCellDesc: {
    margin: "auto",
    marginTop: 5,
    marginLeft: 3,
    marginRight: 3,
    marginBottom: 12,
    fontSize: 10,
    textAlign: "justify",
  },
});

const tables_c = StyleSheet.create({
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    fontSize: 10,
  },
  tableRow: {
    flexDirection: "row",
    fontWeight: "semibold",
  },
  tableRowDatas: {
    flexDirection: "row",
    lineHeight: 1.25,
    minHeight: 40,
  },
  tableCellNumberHead: {
    width: "6%",
    textAlign: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 8,
    paddingBottom: 8,
  },
  tableCellKegiatanHead: {
    width: "34%",
    textAlign: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 8,
    paddingBottom: 8,
  },
  tableCellKeteranganHead: {
    width: "60%",
    textAlign: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 8,
    paddingBottom: 8,
  },
  tableColNumber: {
    width: "6%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
  },
  tableColKegiatan: {
    width: "34%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    flexDirection: "col",
    justifyContent: "center",
    padding: 5,
  },
  tableColKeterangan: {
    width: "60%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "justify",
    flexDirection: "col",
    justifyContent: "center",
    padding: 3,
  },
  notes: {
    fontSize: 9,
    marginTop: 5,
    marginBottom: 5,
  },
  tableSaran: {
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    padding: 5,
    textAlign: "justify",
    minHeight: 60,
    lineHeight: 1.25,
  },
});

const tables_e = StyleSheet.create({
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: "auto",
    flexDirection: "row",
    lineHeight: 1.25,
    fontWeight: "semibold",
  },
  tableNoHead: {
    width: "6%",
    margin: "auto",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderRightWidth: 1,
  },
  tableMuatanHead: {
    width: "60%",
    margin: "auto",

    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderRightWidth: 1,
  },
  tablePKHead: {
    width: "34%",
    margin: "auto",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderRightWidth: 1,
  },
  labelSpan: {
    display: "absolute",
    transformOriginX: 30,
    transformOriginY: 10,
    paddingTop: 10.8,
    paddingBottom: 3,
  },
  tablePKSubHead: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  tablePKSubHeadNP: {
    width: "50%",
    textAlign: "center",
    margin: "auto",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    paddingTop: 2,
  },
  tablePKSubHeadNP2: {
    width: "50%",
    textAlign: "center",
    margin: "auto",
    borderStyle: "solid",
    borderTopWidth: 1,
    paddingTop: 2,
  },
  tablePKSubHeadNone: {
    width: "100%",
    fontSize: 3,
    textAlign: "center",
    margin: "auto",
    borderStyle: "solid",
    paddingTop: 4,
    color: "white",
  },
  label: {
    paddingTop: 3,
    paddingBottom: 3,
  },
  tableDataContainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
  dataNumber: {
    width: "6%",
    margin: "auto",
    flexDirection: "col",
    alignItems: "center",
    justifyContent: "center",
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    padding: 3,
  },
  dataAspek: {
    width: "60%",
    margin: "auto",
    flexDirection: "col",
    justifyContent: "center",
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    paddingLeft: 5,
    padding: 3,
  },
  dataValue: {
    width: "17%",
    margin: "auto",
    flexDirection: "col",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    padding: 3,
  },
});

const tables_f = StyleSheet.create({
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    fontSize: 10,
  },
  containerRowHead: {
    flexDirection: "row",
    lineHeight: 1.25,
    minHeight: 25,
    fontWeight: "semibold",
  },
  containerRow: {
    flexDirection: "row",
    lineHeight: 1.25,
    minHeight: 20,
  },
  containerRowPrestasiHead: {
    flexDirection: "row",
    lineHeight: 1.25,
    minHeight: 25,
    fontWeight: "semibold",
  },
  containerRowPrestasi: {
    flexDirection: "row",
    lineHeight: 1.25,
    minHeight: 35,
  },
  dataNoHead: {
    width: "6%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    paddingTop: 2,
    paddingBottom: 2,
  },
  dataAspekHead: {
    width: "34%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    paddingTop: 2,
    paddingBottom: 2,
  },
  dataKeteranganHead: {
    width: "60%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    paddingTop: 2,
    paddingBottom: 2,
  },
  dataNo: {
    width: "6%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
  },
  dataAspek: {
    width: "34%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    paddingLeft: 5,
    paddingRight: 5,
    flexDirection: "col",
    justifyContent: "center",
  },
  dataKeterangan: {
    width: "60%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    paddingLeft: 5,
    paddingRight: 5,
    flexDirection: "col",
    justifyContent: "center",
  },
  dataKehadiran: {
    width: "100%",
    borderStyle: "solid",
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    textAlign: "center",
    flexDirection: "col",
    justifyContent: "center",
    paddingTop: 2,
    paddingBottom: 2,
  },
});

const tables_ttd = StyleSheet.create({
  table: {
    marginTop: 30,
    textAlign: "center",
    flexDirection: "row",
    fontSize: 11,
  },
  containerRow: {
    width: "50%",
    flexDirection: "col",
    lineHeight: 1.25,
    gap: 2,
  },
  containerRowFull: {
    width: "100%",
    flexDirection: "col",
    lineHeight: 1.25,
    gap: 2,
  },
  param: {
    marginTop: 50,
  },
  guru: {
    textDecoration: "underline",
  },
});

export { main, cover, tables_b, tables_c, tables_e, tables_f, tables_ttd };
